### ISSUE TITLE
support gatsby v3 

### ISSUE THREAD

**Issue by kashesandr** [leopq/gatsby-source-parse#1]
Could you please update the code so it might work with Gatsby v3?

```
Removal of boundActionCreators
The deprecated API boundActionCreators was removed. Please rename its instances to actions to keep the same behavior. For example, in your gatsby-node.js file:

gatsby-node.js

exports.createPages = (gatsbyArgs, pluginArgs) => {
    - const { boundActionCreators } = gatsbyArgs
    + const { actions } = gatsbyArgs
}
```

[https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#removal-of-boundactioncreators](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#removal-of-boundactioncreators)

**Comment by leonardoquevedox** [comment]
Sure, @kashesandr! Fixed it on version `1.5.7` 
All you need is to run  `$ yarn add gatsby-source-parse@latest` in order to use it. 
Thanks for the heads up 🤘
